### ISSUE TITLE
Document schema changes

### ISSUE THREAD

**Issue by bmcfee** [marl/jams-update-2015#1]
- [x] dropped top-level tasks, moved to namespaces and Annotations array
- [x] unified annotation coding (time, duration, value, confidence)
  - [x] dropped atomic types (3.1.1 in the original paper)
  - [x] explicit timing for all observations.  events = 0 duration, track-level = track duration
- [x] per-task schema

**Comment by justinsalamon** [comment]
I can't think of anyone better suited to writing this than @bmcfee, but let me know if I can help with any part of the document.

**Comment by bmcfee** [comment]
aw shucks!

Do you have the source/figures from the original paper handy?  It'd be useful to replicate and modify fig.1 to illustrate the structural changes.

**Comment by justinsalamon** [comment]
I made the first draft of fig 1, but the final sexy version was generated by @ejhumphrey (who should have the source)

**Comment by ejhumphrey** [comment]
Acknowledged, will fish that out next time I'm on that machine.
