### ISSUE TITLE
Document implementation changes

### ISSUE THREAD

**Issue by bmcfee** [marl/jams-update-2015#2]
- [x] dataframe backing
- [x] object search/query mechanism
- [x] mir_eval integration
- [x] dynamic / extensible namespaces
- [x] strict/lax validation
- [x] simplified API
  - ... be more specific here
- [x] IO compression

**Comment by bmcfee** [comment]
The extended document is basically done, except for:
- A section about quickview (which we can axe)
- A figure demonstrating the schema differences -- paging @ejhumphrey

Since our milestone is coming up monday, it would be great if folks could give it a once-over.

**Comment by justinsalamon** [comment]
will give it a read first thing tomorrow morning.

**Comment by justinsalamon** [comment]
@bmcfee see comments here: https://goo.gl/tktVIi

**Comment by bmcfee** [comment]
> @bmcfee see comments here: https://goo.gl/tktVIi

Post won't load.  Maybe share it from kami directly?

**Comment by justinsalamon** [comment]
That's odd, works for me (just tried viewing it with a different account). Sharing the link seems to be the only way to add collaborators now. Are you sure it's not a local issue (browser? some plugin blocking it?). If you still can't get it to open let me know and I'll just export it and send you the PDF.

**Comment by bmcfee** [comment]
Got it to work.  Thanks for the comments!  Responses are on the shared doc.

**Comment by bmcfee** [comment]
Ok, I think the new draft takes into account most of @justinsalamon's comments.

Everyone else: please look this over ASAP and let me know if there are any glaring errors.  If not, I'll start trimming down to make the LBD abstract.

**Comment by justinsalamon** [comment]
@bmcfee I still think table 1 (and to a lesser degree table 2) are hard to read without some type of horizontal separation (be it a line or some type of shading)
