### ISSUE TITLE
Poster or quickview demo?  both?

### ISSUE THREAD

**Issue by bmcfee** [marl/jams-update-2015#4]
Anyone (ahem @ejhumphrey) feel like putting this together?

It can be dead simple, and we can try to get it printed in .es the week of the conference.

**Comment by ejhumphrey** [comment]
Looping back on offline convos, poster will be more feasible for me given various time constraints.

**Comment by justinsalamon** [comment]
Just had a quick look at the poster draft @ejhumphrey, at the risk of proposing more work (and not being able to help because I'm out of cycles right now), I think it could be nice to have something a little closer to the mir_eval poster from last year, i.e. add some code snippets to show how basic stuff can be done in jams 0.2, and perhaps the before/after examples of the jams format from the extended abstract (or an excerpt of each). Just suggestions :)

**Comment by bmcfee** [comment]
I like the layout.  I don't think code snippets are totally necessary, but it would make sense for things like search and eval integration.

Before-and-after examples would probably be inscrutable in poster form.

**Comment by justinsalamon** [comment]
@bmcfee hmm yeah, no wonder the mir_eval poster didn't win best poster presentation. Wait...
(I kid, I kid)

**Comment by ejhumphrey** [comment]
Handful of thoughts:
- This is the first time I've tried to layout a poster in Google Slides and I'm finding I have no point of reference for how large or (my fear) small text will actually render. Given space / content constraints, I agree, I don't think before-and-afters probably won't be worth the trouble. For a first crack, I opted for readability over dense content, which brings us to...
- Serious question: "What is the point of the poster?" It shouldn't and honestly can't be a tutorial, so a lot of the how-to's will be missing. That said, we _do_ want people to be interested, get involved, and download / try / love the thing. One way to facilitate that conversion is by having particular instances of "well isn't that shiny / easy / the best thing you ever saw". I'd be keen to get takes on what folks think those features are.
- "snippets make sense for search and mir_eval", +1 -- this feeds into the previous point.
- It's a google doc, so (a) anyone's free to put cycles against it as they find them and (b) the revision history is tracked, if anything gets totally fubared ... I don't entirely have cycles either.
- FWIW, this is a LBD poster, and `mir_eval` won best poster _presentation_ on its clear relevance to the community and Colin's charisma, exuberance, and indefatigable badassery.

**Comment by justinsalamon** [comment]
> Serious question: "What is the point of the poster?" It shouldn't and honestly can't be a tutorial, so a lot of the how-to's will be missing. That said, we do want people to be interested, get involved, and download / try / love the thing. One way to facilitate that conversion is by having particular instances of "well isn't that shiny / easy / the best thing you ever saw". I'd be keen to get takes on what folks think those features are.

+1. So, if we're going the "jams is awesome use it" route rather than a tutorial route, how about we try and make it a tad more "ad-like"? I think the point of the poster is to get everyone who sees it to at least download jams and try it once. Maybe a loud tag-line a la "Synchronized annotations for multiple MIR tasks in a single structured format with a python API? YES PLEASE". (this, clearly, can be improved upon)

> FWIW, this is a LBD poster, and `mir_eval` won best poster presentation on its clear relevance to the community and Colin's charisma, exuberance, and indefatigable badassery.

Don't sell yourself short ;)

**Comment by ejhumphrey** [comment]
I was thinking ad-like + release notes in poster form ... which, actually, kind of reminds me of an [app description layout](https://itunes.apple.com/us/app/learn-music-musicpal/id976261614) in the app store.

Apologies for the shameless self promotion, but I had it open.

@bmcfee, does this totally cut across your moral fiber(s)?

> Don't sell yourself short ;)

p.s. Then I'd offer `correlation != causation` :o)

**Comment by bmcfee** [comment]
@ejhumphrey ![moral fiber](http://www.morethings.com/fan/o_brother_where_art_thou/o_brother_pardoned-126.jpg)

**Comment by ejhumphrey** [comment]
so ... you like the idea?

**Comment by bmcfee** [comment]
I'd the abstract ready to go? We should submit it.

**Comment by justinsalamon** [comment]
What happened with this in the end?

**Comment by bmcfee** [comment]
We were too late to get the LBD session in 2015?

**Comment by justinsalamon** [comment]
Anyone feel like picking up the torch for 2016? Still well worth it I think.

**Comment by justinsalamon** [comment]
![tumbleweed](http://i.giphy.com/Az1CJ2MEjmsp2.gif)

**Comment by rabitt** [comment]
Looks like you've volunteered yourself ;)

**Comment by justinsalamon** [comment]
I think @ejhumphrey was already invested and done most work on the potential poster - time to see it through EJ 👊

**Comment by bmcfee** [comment]
![cooks](http://i.giphy.com/TlK63EuYIQ1hMsMJMUo.gif)
